### ISSUE TITLE
Upgrade font awesome to 4.7.0

### ISSUE THREAD

**Issue by jonathanbardo** [godaddy/wp-contact-widgets#34]
Since font awesome is backward compatible, we should upgrade the library to get the latest icons.

**Comment by fjarrett** [comment]
@jonathanbardo This was done by @EvanHerman in https://github.com/godaddy/wp-contact-widgets/pull/22/commits/0ae298ffb3bfae02fbdfd33b584d65ec19dfa525 as part of #22. However, I think we should consider bundling FA instead of using a CDN.

Having the CSS on the same domain means it can be concatenated with caching plugins (like [Dep Min](https://wordpress.org/plugins/dependency-minification/)) and you have control over the cache expiration header.

**Comment by jonathanbardo** [comment]
@fjarrett Actually we should leave it up to the user to decide with an option.

**Comment by fjarrett** [comment]
@jonathanbardo So you mean bundle FA and make the URI filterable?

**Comment by jonathanbardo** [comment]
@fjarrett Or bundle fa and expose a filter to use the CDN instead?

**Comment by fjarrett** [comment]
@jonathanbardo Yes that works, I was just thinking in case someone wants to use some specific version of FA (or even a compatible fork of FA) they could just easily swap the CDN URI. So maybe there could actually be two filters?

```php
// Use bundled FA by default
apply_filters( 'wpcw_widget_social_use_cdn', false );

// Default CDN URI, if enabled
apply_filters( 'wpcw_widget_social_cdn_uri', 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' );
```

**Comment by jonathanbardo** [comment]
@fjarrett Yes let's go with 2 filters 👍
