### ISSUE TITLE
Add YouTube Icon

### ISSUE THREAD

**Issue by Hegad** [godaddy/wp-contact-widgets#59]
YouTube is one of the most popular video platforms and should be included into the plugin.

**Comment by EvanHerman** [comment]
Hi @Hegad,

We used to include the YouTube icon, but due to the way the YouTube channel URLs differ between legacy channels and the newer channels we decided to deprecate YouTube from the selectable list.

https://github.com/godaddy/wp-contact-widgets/blob/develop/includes/social-networks.php#L47-L51

However, as you can see in the above code the YouTube icon is still included in the plugin and all you would need to do is re-enable it and populate the URL field with the proper URL for your channel.

You can add the following to your child themes functions.php file, or create an MU plugin and add the following snippet to it to re-enable the YouTube icons.

```php
function contact_widgets_reenable_youtube( $networks, $instance ) {

   unset( $networks['youtube']['deprecated'] );

   return $networks;

}
add_filter( 'wpcw_widget_contact_fields', 'contact_widgets_reenable_youtube', 10, 2 );
```

Once added, that should make the YouTube icon selectable again.

Also see the following issue, where it was removed:
https://github.com/godaddy/wp-contact-widgets/pull/24
