### ISSUE TITLE
Please Add  Line Social profile

### ISSUE THREAD

**Issue by NerdRole** [godaddy/wp-contact-widgets#60]
Could you please add Line Social icon

Line Social is this company 
https://line.me/en/

i check a little fontawesome version 4 not have line but version 5 have i dont know how to update that in polugin

**Comment by EvanHerman** [comment]
Hi @NerdRole 

We have a filter included in the plugin to enable Font Awesome 5 instead of Font Awesome 4. Once you do that, you can use the filter `` to add your custom Line social icon.

The following code snippet will first enable Font Awesome 5 and then add the custom Line social icon. You will want to add this into your child themes `functions.php` file, or create a custom [MU plugin](https://godaddy.github.io/wp-primer-theme/tutorials-and-examples/tutorials/mu-plugin.html) to add this code into. Once you add it, you should see the Line icon available to select from in the social widget.

```php
/**
 * Contact Widgets - Enable Font Awesome 5
 */
add_filter( 'wpcw_social_icons_fontawesome_5', '__return_true' );

/**
 * Add Custom Line Icon
 */
add_filter( 'wpcw_widget_social_custom_fields', function ( $fields, $instance ) {

  $fields['line'] = [
    'icon'      => 'line', // See font-awesome icon slug
    'prefix'    => 'fab', // See font-awesome icon prefix
    'label'     => __( 'Line', 'YOURTEXTDOMAIN' ),
    'default'   => 'https://line.com/username',
    'select'    => 'username',
    'sanitizer' => 'esc_url_raw',
    'escaper'   => 'esc_url',
    'social'    => true,
    'target'    => '_blank',
  ];

  return $fields;

}, 10, 2 );
```

Please note, you will probably want to update the 'default' value in the array to reflect the proper user profile URL for line. I've not used the service before so I'm not familiar with the URL structure for user profiles.

#### Example

<img src="https://cldup.com/pPkT66EB3v.png" width="350" />

Let us know how that goes or if you have any questions!

Evan
